# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# NeoForge Properties
# check these on https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.251
neo_version_range=[21.1.251,)
loader_version_range=[4,)
moddev_version=2.0.147

# Mod Properties
mod_id=waylandcraft
mod_version=2.1.0
maven_group=dev.evvie.waylandcraft
archives_base_name=waylandcraft

# Dependencies
concentus_version=1.0.2
iris_version=1.8.14-beta.1+1.21.1-neoforge
